language: c

matrix:
    include:
        - os: linux
          dist: bionic
          compiler: gcc
        - os: linux
          dist: bionic
          compiler: clang
        - os: linux
          dist: xenial
          compiler: gcc
        - os: linux
          dist: xenial
          compiler: clang
        - os: osx
          osx_image: xcode11.3
          compiler: gcc
        - os: osx
          osx_image: xcode11.3
          compiler: clang
        - os: osx
          osx_image: xcode9.4
          compiler: gcc
        - os: osx
          osx_image: xcode9.4
          compiler: clang
        - os: osx
          osx_image: xcode6.4
          compiler: gcc
        - os: osx
          osx_image: xcode6.4
          compiler: clang

addons:
    homebrew:
        update: true
        brewfile: true
    apt:
        packages:
            - autoconf
            - automake
            - libtool
            - m4
            - libudev-dev
        sources:
            - ubuntu-toolchain-r-test

script:
    - ./travis-autogen.sh && make -j4
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make clean && ./travis-autogen.sh --disable-udev && make -j4 ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd Xcode && xcodebuild -project libusb.xcodeproj ; fi
